services:
  wedding-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/lo-wedding/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    container_name: lukene-osvaldo-wedding
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
